### ISSUE TITLE
Missing dependency/blueprints: ember-frost-core, ember-frost-sort

### ISSUE THREAD

**Issue by quincyle** [ciena-frost/ember-frost-pick-list#9]

**Comment by notmessenger** [comment]
`ember-frost-sort` should be added to the `dependencies` of _package.json_ and _not_ the blueprint.

Check with @notmessenger before adding `ember-frost-core` to the blueprint - he is currently undertaking related efforts on a larger scale.

**Comment by notmessenger** [comment]
Will be evaluated in #12

**Comment by juwara0** [comment]
Closed via: https://github.com/ciena-frost/ember-frost-pick-list/pull/13
